compatibility_date = "2022-04-15"
compatibility_flags = []
kv_namespaces = [
  {binding = "COMMON", id = "b817e26540f1471196ca44494da06e93", preview_id = "b817e26540f1471196ca44494da06e93"},
]
name = "powercuts-schedule-lk"
route = ''
type = "javascript"
account_id = "84852d6800f7db35978215369b76b2b7"
usage_model = ''
workers_dev = true
zone_id = ''

[build]
command = "pnpm build"

[build.upload]
format = "service-worker"

[miniflare]
kv_persist = true # Defaults to ./.mf/kv
